apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kalium-ves-price
  namespace: kalium
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: boompow
            image: replaceme
            command: ["/bin/bash", "-c"]
            args: ["python vesprice.py"]
            env:
              - name: REDIS_HOST
                value: redis-0.redis
              - name: REDIS_DB
                value: "15"
          restartPolicy: OnFailure