apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: natrium-prices
  namespace: natrium
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: boompow
            image: replaceme
            command: ["/bin/bash", "-c"]
            args: ["python prices.py"]
            env:
              - name: REDIS_HOST
                value: redis-0.redis
              - name: REDIS_DB
                value: "10"
          restartPolicy: OnFailure